### ISSUE TITLE
Backend Request Logic

### ISSUE THREAD

**Issue by jerry-hall** [jerry-hall/tesla-automation-scheduler#4]
Need to implement backend request logic. This logic will need to use Amazon SQS SDK. Check out https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples.html for examples

**AC:**

- Implement
  - [x] Send climate request logic
  - [x] Send charging request logic
  - [x] Schedule climate request logic
  - [x] Schedule charging request logic
  - [x] Respond to request with error/success messages

**Comment by jerry-hall** [comment]
**TODO:** 

Add environment variables to container:

- REGION
- APIVERSION ("2012-11-05" default)
- SQS_QUEUE_URL

**Moved to #10**

**Comment by jerry-hall** [comment]
The issue is completed for the most part. There may be improvements to be made in the future wrt. more descriptive error messages. For the scope of this quick project thus far, the work completed is sufficient.
